/**
 * Export utilities for generating downloadable analysis reports.
 */

/**
 * Generate a markdown report from mission analysis data.
 * @param {Object} mission - Mission data
 * @param {Object} analysis - Analysis results
 * @param {Object} review - Optional analyst review
 * @returns {string} Formatted markdown content
 */
export function generateMarkdown(mission, analysis, review = null) {
    const timestamp = new Date().toISOString().split('T')[0];
    const missionName = mission?.filename || mission?.source_label || 'Mission Analysis';

    let markdown = `# ${missionName}

**Generated:** ${new Date().toLocaleString()}  
**Mission ID:** \`${mission?.mission_id || 'N/A'}\`  
**Source Type:** ${mission?.source_type?.toUpperCase() || 'Unknown'}  
**Status:** ${mission?.status || 'Unknown'}

---

## AI Analysis

> ⚠️ **Note:** This analysis was generated by AI and should be reviewed by a qualified analyst.

### Summary

${analysis?.summary_text || 'No summary available.'}

### Risk Classification

**Level:** ${analysis?.risk_level?.toUpperCase() || 'UNKNOWN'}

### Extracted Entities

`;

    // Add entities table
    if (analysis?.extracted_entities?.length > 0) {
        markdown += `| Type | Name | Relevance |
|------|------|-----------|
`;
        for (const entity of analysis.extracted_entities) {
            markdown += `| ${entity.type || 'Unknown'} | ${entity.name || 'Unknown'} | ${entity.relevance || 'N/A'} |
`;
        }
    } else {
        markdown += `*No entities extracted.*

`;
    }

    // Add explanation
    markdown += `
### AI Explanation

${analysis?.explanation || 'No explanation available.'}

---

## Cost Transparency

| Metric | Value |
|--------|-------|
| Input Tokens | ${analysis?.input_tokens || 0} |
| Output Tokens | ${analysis?.output_tokens || 0} |
| Total Tokens | ${analysis?.total_tokens || 0} |
| Estimated Cost | $${(analysis?.estimated_cost || 0).toFixed(4)} |
| Model | ${analysis?.llm_model_used || 'Unknown'} |
| Processing Time | ${analysis?.processing_time_ms ? `${(analysis.processing_time_ms / 1000).toFixed(1)}s` : 'N/A'} |
| Confidence Score | ${analysis?.confidence_score ? `${(analysis.confidence_score * 100).toFixed(0)}%` : 'N/A'} |

`;

    // Add review section if available
    if (review) {
        markdown += `---

## Analyst Review

**Status:** ${review.approved ? '✅ Approved' : '⏳ Pending'}  
**Reviewed:** ${review.reviewed_at ? new Date(review.reviewed_at).toLocaleString() : 'N/A'}

### Analyst Notes

${review.analyst_notes || '*No notes provided.*'}

`;
    }

    // Add footer
    markdown += `---

## Original Content

\`\`\`
${mission?.normalized_content || 'Content not available.'}
\`\`\`

---

*Generated by CACI Mission Intake and Analysis Copilot*
`;

    return markdown;
}

/**
 * Trigger a file download in the browser.
 * @param {string} content - File content
 * @param {string} filename - Name for the downloaded file
 * @param {string} mimeType - MIME type (default: text/markdown)
 */
export function downloadFile(content, filename, mimeType = 'text/markdown') {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    // Clean up the URL object
    URL.revokeObjectURL(url);
}

/**
 * Export analysis as a markdown file.
 * @param {Object} mission - Mission data
 * @param {Object} analysis - Analysis results
 * @param {Object} review - Optional analyst review
 */
export function exportAnalysisToMarkdown(mission, analysis, review = null) {
    const markdown = generateMarkdown(mission, analysis, review);
    const filename = `${(mission?.filename || mission?.source_label || 'analysis').replace(/[^a-z0-9]/gi, '_')}_report.md`;
    downloadFile(markdown, filename);
}
